apiVersion: v1
kind: PersistentVolume
metadata:
  name: znn-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/znn-pv